# Generated by Django 2.1.5 on 2021-02-23 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wishlist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wish_id', models.CharField(default=wishlist.models.gen_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
