# Generated by Django 2.1.5 on 2021-02-23 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(default=product.models.gen_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_img', models.ImageField(blank=True, null=True, upload_to='category_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.CharField(default=product.models.gen_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=500)),
                ('ratings', models.IntegerField(default=0)),
                ('added_date', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(default=product.models.gen_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.CharField(default=product.models.gen_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
                ('tags', models.TextField()),
                ('stocks', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Image')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
