# Generated by Django 2.1.5 on 2021-02-23 08:07

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notify_id', models.CharField(default=dashboard.models.gen_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('notify_type', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('notify_text', models.CharField(max_length=75)),
            ],
        ),
    ]
